### ISSUE TITLE
서버 사망

### ISSUE THREAD

**Issue by woochul2** [woochul2/alexander-photos#3]
서버가 너무 불안정하다. 다음 에러 내면서 자주 뻗어버림..

```json
{
    "errorType": "Error",
    "errorMessage": "MongoNetworkError: connect EHOSTUNREACH 34.84.117.238:27017",
    "stack": [
        "Error: MongoNetworkError: connect EHOSTUNREACH 34.84.117.238:27017",
        "    at Object.connect (/var/task/src/database.js:18:13)",
        "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
    ]
}
```

**Comment by woochul2** [comment]
서버리스 함수는 트래픽이 증가하면 계속해서 DB 커넥션을 만들기 때문에, 트래픽이 증가하면 DB의 커넥션 제한을 초과하여 서버 에러가 나는 것 같다.
